### ISSUE TITLE
'Are there sufficient tests?' failing with Traceback when repo uses `master` instead of `main`

### ISSUE THREAD

**Issue by ryancheley** [ryancheley/the-well-maintained-test#11]
**Describe the bug**
When running on a repo with `master` instead of `main` the following error is given. 

For example `the-well-maintained-test 'https://github.com/scikit-hep/pyhf'`returns

```
Traceback (most recent call last):
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/bin/the-well-maintained-test", line 33, in <module>
    sys.exit(load_entry_point('the-well-maintained-test', 'console_scripts', 'the-well-maintained-test')())
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryan/Documents/github/the-well-maintained-test/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ryan/Documents/github/the-well-maintained-test/the_well_maintained_test/cli.py", line 101, in url
    print(check_tests(tree_url, headers))
  File "/Users/ryan/Documents/github/the-well-maintained-test/the_well_maintained_test/utils.py", line 98, in check_tests
    for i in r.get("tree"):
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**
The name of the default branch should not matter (main, or master or whatever)

**Comment by ryancheley** [comment]
It may be worth looking at an option to pass in the name of the branch to allow review of development branches. Perhaps there is a way to check to the 'default` branch via the GitHub API and use that in the `tree_url` 🤔

**Comment by ryancheley** [comment]
Adding this

```
    api_url = f"https://api.github.com/repos/{author}/{package}"
    default_branch = requests.get(api_url).json().get('default_branch')
```

and then replacing `main` with `{default_branch}` in the urls that were looking at a specific branch fixed the issue (locally at least). 

Still think it's worth looking at adding an option to pass a `branch_name` as an optional argument
